# Generated by Django 4.2.2 on 2023-12-11 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, null=True)),
                ('apellido_paterno', models.CharField(max_length=100, null=True)),
                ('email_academico', models.CharField(max_length=100, null=True)),
                ('titulo_tesis', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('area_academica', models.CharField(max_length=100, null=True)),
                ('clave_encriptacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_u', to='usuarios.usuarios')),
            ],
        ),
    ]
