# Generated by Django 4.2.2 on 2023-11-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0002_alter_tesis_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='estado',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
