# Generated by Django 4.2.2 on 2023-11-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0003_tesis_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='estado',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
