# Generated by Django 4.2.2 on 2023-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0004_alter_tesis_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesis',
            name='estado',
        ),
        migrations.AddField(
            model_name='tesis',
            name='clave_encriptacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
