# Generated by Django 4.2.2 on 2023-12-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_usuario', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email_academico', models.EmailField(max_length=254, unique=True)),
                ('rol_usuario', models.CharField(blank=True, max_length=30)),
                ('area_academica', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
